"""add yandex_access_token

Revision ID: d9199f329c4c
Revises: deb6bdebcb64
Create Date: 2026-02-07 22:23:48.800678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9199f329c4c'
down_revision: Union[str, Sequence[str], None] = 'deb6bdebcb64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserProfile', sa.Column('yandex_access_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserProfile', 'yandex_access_token')
    # ### end Alembic commands ###
